FROM golang:alpine AS builder

COPY . /app/
WORKDIR /app

RUN CGO_ENABLED=0 go build -ldflags '-s -w -extldflags "-static"' -o rest

FROM scratch

WORKDIR /app
COPY --from=builder /app/rest ./rest

EXPOSE 8081

CMD [ "./rest" ]
